server:
  port: 80

spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: database
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace